[build-system]
requires = ["setuptools >= 61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wemulator"
version = "0.0.1a0"
description = "A simple social emulator using AI agents"
authors = [
    { name = "Aerodream Granite", email = "yxdowncomputer@outlook.com" }
]
readme = "README.md"
license = { text = "GNU General Public License v3 (GPLv3)" }
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Games/Entertainment :: Simulation"
]
requires-python = ">=3.8"
dependencies = [
    "openai",
    "dashscope",
    "uuid",
    "gradio"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["wemulator*"]

[project.scripts]
wemu-gradio = "wemulator.webui.webui:main"